version: "3.8"
services:
  db:
    image: postgres:alpine
    container_name: github-app-database
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5400:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    external: false
    